spring.application.name=api-gateway
server.port=8080

# Kết nối tới Discovery Server (Cái cũ bạn đang chạy ở port 8761)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Cấu hình Routing (Định tuyến)
# Yêu cầu bắt đầu bằng /api/product/ sẽ gửi tới service tên là 'product-service'
spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://product-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/product/**

# Yêu cầu bắt đầu bằng /api/order/ sẽ gửi tới service tên là 'order-service'
spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=lb://order-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/order/**

# Yêu cầu bắt đầu bằng /api/notification/ sẽ gửi tới service tên là 'notification-service'
spring.cloud.gateway.routes[2].id=notification-service
spring.cloud.gateway.routes[2].uri=lb://NOTIFICATION_SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/notification/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2

# Expose Actuator và Prometheus để giám sát
management.endpoints.web.exposure.include=health,prometheus